name: setup devenv
description: prepares devenv with cachix
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: devenv
    - name: install devenv
      shell: bash
      run: nix profile install nixpkgs#devenv
