name: setup environment
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: devenv
    - name: install devenv
      run: nix profile install nixpkgs#devenv
