name: use pnpm cache
description: caches pnpm store directory between workflow runs
runs:
  using: "composite"
  steps:
    - name: retrieve pnpm store directory
      shell: devenv shell bash -- -e {0}
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v5
      id: pnpm-cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
    - name: check cache
      if: steps.pnpm-cache.outputs.cache-hit != 'true'
      shell: bash
      run: devenv shell pnpm i --frozen-lockfile
